appname: kexa-helm

namespace: default

kubernetesAddon:
  enabled: true
  mountPath: kubernetesconfigurations


postgresql:
  image:
    tag: "15.0.0"
  global:
    postgresql:
      auth:
        postgresPassword: my_postgres_password
        username: kexa_postgres_user
        password: my_postgres_password
  livenessProbe:
    initialDelaySeconds: 200
  readinessProbe:
    initialDelaySeconds: 200
  host: my-postgresql.default.svc.cluster.local
  fullnameOverride: "my-postgresql"
  connectionString: "postgresql://kexa_postgres_user:my_postgres_password@my-postgresql.default.svc.cluster.local:5432/kexa_export_database"
  auth:
    postgresPassword: my_postgres_password
    username: kexa_postgres_user
    password: my_postgres_password
    database: kexa_export_database
  service:
    port: 5432
  primary:
    service:
      port: 5432
    initdb:
      scripts:
        init.sql: |
          CREATE DATABASE kexa_export_database;
          CREATE USER grafanareader WITH PASSWORD 'password';
          CREATE USER kexa_postgres_user WITH PASSWORD 'my_postgres_password';
          
          GRANT ALL PRIVILEGES ON DATABASE kexa_export_database TO kexa_postgres_user;
          GRANT ALL ON SCHEMA public TO kexa_postgres_user;

          \c kexa_export_database
          
          GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO kexa_postgres_user;
          GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO kexa_postgres_user;
          GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO kexa_postgres_user;

          ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO kexa_postgres_user;
          ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO kexa_postgres_user;
          ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO kexa_postgres_user;
          
          GRANT USAGE ON SCHEMA public TO grafanareader;
          GRANT SELECT ON ALL TABLES IN SCHEMA public TO grafanareader;
  persistence:
    enabled: true
    size: 10Gi

grafana.ini:
  database:
    type: "postgres"
    host: "my-postgresql.default.svc.cluster.local"
    name: "kexa_export_database"
    user: "kexa_postgres_user"
    password: "my_postgres_password"
    ssl_mode: "disable"


grafana:
  config:
    grafana.ini:
      dashboards:
        path: /var/lib/grafana/dashboards
  securityContext:
    fsGroup: 472
    runAsUser: 472
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      defaultFolderName: General
      foldersFromFilesStructure: true
      searchNamespace: ALL
  dashboardsProvider:
    enabled: true
    configMapName: grafana-dashboards
  volumeMounts:
    - name: dashboard
      mountPath: /var/lib/grafana/dashboards
  volumes:
    - name: dashboard
      configMap:
        name: grafana-dashboards
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: postgres-kexa-datasource
        editable: false
        type: postgres
        access: proxy
        url: my-postgresql.default.svc.cluster.local:5432
        user: kexa_postgres_user
        isDefault: false
        secureJsonData:
          password: my_postgres_password
        database: kexa_export_database
        jsonData:
          sslmode: "disable"
          postgresVersion: 1500
          timescaledb: false
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      defaultNamespace: default
  volumeMounts:
    - name: dashboards
      mountPath: /var/lib/grafana/dashboards
  volumes:
    - name: dashboards
      configMap:
        name: grafana-dashboards


kexaScript:
  image: innovtech/kexa
  tag: latest
  volumeMounts:
    - name: configuration-files
      mountPath: /app/config
  volumes:
    - name: configuration-files
      configMap:
        name: kexa-configuration-files
  saveAddon:
    type: postgres
    name: "Clever Cloud Postgresql"
    urlName: postgres_connect
    description: "Database to save the data (clever-cloud)"

rundeck:
  image:
    repository: jordan/rundeck #adriencloud/rundeck-kube-python
    tag: latest