apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appname }}-cronicle-svc"
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cronicle
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3012