apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-dind-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appname }}-dind
  ports:
    - protocol: TCP
      port: 2375
      targetPort: 2375