apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-binding
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.appname }}-hook-service-account
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.appname }}-secret-upload-role
  apiGroup: rbac.authorization.k8s.io