apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appname }}-secret-upload-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: [ "create", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["kexa-configuration-secret"]
    verbs: ["get"]