apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appname }}-kexa-rules-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.hostConfigPath }}
  storageClassName: {{ .Values.appname }}-rules-storage-class
  persistentVolumeReclaimPolicy: Delete