apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appname }}-kexa-rules-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.appname }}-rules-storage-class