apiVersion: v1
kind: Secret
metadata:
  name: kexa-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  postgres-connection-string: {{ .Values.postgresql.connectionString | b64enc | quote }}
