appname: kexa-helm

namespace: default

kubernetesAddon: # Enable or disable kubernetes addon
  enabled: true
  mountPath: kubernetesconfigurations # where to mount: this has to be the same as the path in your .env file
                                      # ex: KUBECONFIG=./kubernetesconfigurations/kubeconfig.yaml


postgresql:
  postgresPassword: my_postgres_password 
  username: kexa_postgres_user
  password: my_postgres_password
  database: kexa_export_database
  host: my-postgresql.default.svc.cluster.local
  fullnameOverride: "my-postgresql"
  connectionString: "postgresql://kexa_postgres_user:my-postgresql.default.svc.cluster.local:5432/kexa_export_database"
  auth:
    postgresPassword: my_postgres_password
    username: kexa_postgres_user
    password: my_postgres_password
    database: kexa_export_database
  service:
    port: 5432
  primary:
    service:
      port: 5432
    initdb:
      scripts:
        init.sql: |
          CREATE DATABASE kexa_export_database;
          CREATE USER grafanareader WITH PASSWORD 'password';
          CREATE USER kexa_postgres_user WITH PASSWORD 'my_postgres_password';
          GRANT USAGE ON SCHEMA schema TO grafanareader;
          GRANT SELECT ON schema.table TO grafanareader;
  persistence:
    enabled: true
    size: 10Gi


grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: PostgreSQL
          type: postgres
          access: proxy
          orgId: 1
          url: my-postgresql.default.svc.cluster.local:5432
          user: kexa_postgres_user
          password: my_postgres_password
          database: kexa_export_database
          jsonData:
            sslmode: "disable"
            postgresVersion: 1200
            timescaledb: true
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      defaultNamespace: default
  volumeMounts:
    - name: dashboards
      mountPath: /var/lib/grafana/dashboards
  volumes:
    - name: dashboards
      configMap:
        name: grafana-dashboards


kexaScript:
  image: innovtech/kexa
  tag: latest
  volumeMounts:
    - name: configuration-files
      mountPath: /app/config
  volumes:
    - name: configuration-files
      configMap:
        name: kexa-configuration-files
  saveAddon:
    type: postgres
    name: "Clever Cloud Postgresql"
    urlName: postgres_connect
    description: "Database to save the data (clever-cloud)"