appname: kexa-helm

namespace: default

kubernetesAddon: # Enable or disable kubernetes addon
  enabled: true
  mountPath: kubernetesconfigurations # where to mount: this has to be the same as the path in your .env file
                                      # ex: KUBECONFIG=./kubernetesconfigurations/kubeconfig.yaml


postgresql:
  host: postgresql.default.svc.cluster.local
  database: your_database_name
  username: postgres
  password: your_password
  auth:
    postgresPassword: my_postgres_password
  primary:
    service:
      port: 5432


grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: PostgreSQL
          type: postgres
          access: proxy
          orgId: 1
          url: postgresql-postgresql.default.svc.cluster.local:5432
          user: postgres
          password: my_postgres_password
          database: postgres
          jsonData:
            sslmode: "disable"
            postgresVersion: 1200
            timescaledb: true
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      defaultNamespace: default
  volumeMounts:
    - name: dashboards
      mountPath: /var/lib/grafana/dashboards
  volumes:
    - name: dashboards
      configMap:
        name: grafana-dashboards


kexaScript:
  image: innovtech/kexa
  tag: latest
  volumeMounts:
    - name: configuration-files
      mountPath: /app/config
  volumes:
    - name: configuration-files
      configMap:
        name: kexa-configuration-files