apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.appName }}-job"
spec:
  template:
    spec:
      containers:
      - name: "{{ .Values.appName }}-job-container"
        image: "{{ .Values.kexaScript.image }}:{{ .Values.kexaScript.tag }}"
        command: ["pnpm", "run", "start"]
        env:
          - name: POSTGRES_HOST
            value: "{{ .Values.postgresql.host }}"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.appName }}-postgresql"
                key: postgresql-username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.appName }}-postgresql"
                key: postgresql-password
          - name: POSTGRES_DB
            value: "{{ .Values.postgresql.database }}"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
      restartPolicy: Never